# Generated by Django 4.2.7 on 2025-06-05 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_remaining', models.IntegerField(default=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('input_text', models.TextField()),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('width', models.PositiveIntegerField(default=800)),
                ('height', models.PositiveIntegerField(default=400)),
                ('font', models.CharField(choices=[('arial', 'Arial'), ('times', 'Times New Roman'), ('courier', 'Courier New'), ('verdana', 'Verdana'), ('georgia', 'Georgia'), ('trebuchet', 'Trebuchet MS'), ('comic', 'Comic Sans MS')], default='arial', max_length=20)),
                ('color_scheme', models.CharField(choices=[('default', 'Default'), ('blues', 'Blues'), ('reds', 'Reds'), ('greens', 'Greens'), ('purples', 'Purples'), ('oranges', 'Oranges'), ('greys', 'Greys'), ('rainbow', 'Rainbow')], default='default', max_length=20)),
                ('background_color', models.CharField(default='white', max_length=20)),
                ('max_words', models.PositiveIntegerField(default=200)),
                ('word_density', models.PositiveIntegerField(default=80)),
                ('orientation', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical'), ('random', 'Random')], default='random', max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('svg_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_clouds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]